CREATE TABLE IF NOT EXISTS movies (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    genre TEXT NOT NULL,
    language TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    release_date DATE NOT NULL,
    rating NUMERIC(3,1) NOT NULL DEFAULT 0.0,
    poster_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO movies (
    id,
    title,
    description,
    genre,
    language,
    duration_minutes,
    release_date,
    rating,
    poster_url,
    is_active,
    created_at,
    updated_at
)
VALUES
    (
        'mov_001',
        'Dune: Part Two',
        'Paul Atreides unites with the Fremen of Arrakis to wage war against those who destroyed his family.',
        'Sci-Fi',
        'English',
        166,
        '2024-03-01',
        8.5,
        'https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_002',
        'Oppenheimer',
        'The story of J. Robert Oppenheimer and the Manhattan Project during World War II.',
        'Biography',
        'English',
        180,
        '2023-07-21',
        8.4,
        'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_003',
        'Barbie',
        'Barbie and Ken have the time of their lives in the real world.',
        'Comedy',
        'English',
        114,
        '2023-07-21',
        6.9,
        'https://upload.wikimedia.org/wikipedia/en/0/0b/Barbie_2023_poster.jpg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_004',
        'Spider-Man: Across the Spider-Verse',
        'Miles Morales catapults across the multiverse with a team of Spider-People.',
        'Animation',
        'English',
        140,
        '2023-06-02',
        8.4,
        'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_005',
        'John Wick: Chapter 4',
        'John Wick uncovers a path to defeating the High Table.',
        'Action',
        'English',
        169,
        '2023-03-24',
        7.7,
        'https://upload.wikimedia.org/wikipedia/en/d/d0/John_Wick_-_Chapter_4_promotional_poster.jpg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_006',
        'The Dark Knight',
        'Batman faces the Joker as he wreaks havoc on Gotham City.',
        'Action',
        'English',
        152,
        '2008-07-18',
        9.0,
        'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_007',
        'Inception',
        'A thief who steals secrets through dreams is offered a shot at redemption.',
        'Sci-Fi',
        'English',
        148,
        '2010-07-16',
        8.8,
        'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'mov_008',
        'Everything Everywhere All at Once',
        'An unlikely hero must save the multiverse when her family and taxes collide.',
        'Action',
        'English',
        139,
        '2022-03-25',
        7.8,
        'https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg',
        TRUE,
        NOW(),
        NOW()
    )
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    genre = EXCLUDED.genre,
    language = EXCLUDED.language,
    duration_minutes = EXCLUDED.duration_minutes,
    release_date = EXCLUDED.release_date,
    rating = EXCLUDED.rating,
    poster_url = EXCLUDED.poster_url,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();
